version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - dev-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    volumes:
      - /home/drigolx/Dev/redisdb:/db
      #- C:\redis-ex:/db
    depends_on:
      - redis
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
# access http://localhost:8001/ to RedisInsight
# on connection, try localhost on host value, if dont pass, try IP address of your machine
