version: "3.7"

services:
  redis:
    image: redis:latest
    container_name: redis
    user: root
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - C:\containers\redis\redis:/data
    networks:
      - dev-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 10s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    user: root
    ports:
      - "8001:8001"
    volumes:
      - C:\containers\redis\redisinsight:/db
    depends_on:
      redis:
        condition: service_started
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
