version: "3.7"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002  --location /workspace --debug /workspace/debug.log"
    user: root
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    environment:
      AZURITE_ACCOUNTS: devstoreaccount1
    networks:
      - dev-network
    volumes:
      - C:\containers\azurite:/workspace

networks:
  dev-network:
    driver: bridge
