version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    user: root
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - dev-network
    volumes:
      - C:\containers\rabbitmq\data:/var/lib/rabbitmq/
      - C:\containers\rabbitmq\log:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

networks:
  dev-network:
    driver: bridge
