apiVersion: v1
kind: Secret

metadata:
  name: pgadmin-secret
  namespace: default
  labels:
    app: pgadmin

data:
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4xMjM=
stringData: 
  PGADMIN_DEFAULT_EMAIL: email@teste.com
