kind: Service
apiVersion: v1

metadata:
  namespace: default
  name: pgadmin-svc

spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
