apiVersion: v1
kind: PersistentVolume

metadata:
  namespace: default
  name: postgres-pv

spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minikube/directory/structure/"
    type: DirectoryOrCreate
