apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: default
  name: postgres-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
