apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: default
  labels:
    app: postgres

data:
  POSTGRES_PASSWORD: YWRtaW4xMjM=
stringData: 
  POSTGRES_USER: admin
  POSTGRES_DB: postgresdb
